### ISSUE TITLE
Fix screensaver issues (xscreensaver is missing) 

### ISSUE THREAD

**Issue by THS-on** [imedias/lernstickAdvanced#15]
Currently the xscreesaver is not working correctly in most desktop environments.
This can be fixed by installing `xscreensaver`.
xfce4-power-manager is used to manage the screensaver in LXDE and XFCE,  starts also in MATE which causes sometimes the screensaver to crash in MATE.
Fix for that is to change in `/etc/xdg/autostart/xfce4-power-manager.desktop`:
```
NotShowIn=GNOME;KDE;Unity;
```
to
```
NotShowIn=GNOME;KDE;Unity;MATE;
```
What is the correct way to modify this file? A normal lernstick-desktop-file-diversions package?

THS-on

**Comment by ronnystandtke** [comment]
Thanks for the info! The issues are fixed by the following commits:
https://github.com/imedias/lernstickAdvanced/commit/2010264c12d4231928cd94e3a37ea821a832dded
https://github.com/imedias/lernstickAdvanced/commit/898c9c36385d62b6ae525b20bd93d21be6348934
https://github.com/imedias/lernstick-desktop-file-diversions/commit/1625e3c7116f951d7975eaea340d51552a4c0fa0
